---
title: "Coronavirus_Map_Feb"
author: "Alex Jonas"
date: "3/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(mosaic)
library(mclust)
library(tidyverse)
library(caret)
library(rpart)
library(rattle)
library(magrittr)
library(dplyr)
```


```{r}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/alex/Desktop")
getwd()
```

```{r}
data <-  read.csv(file = 'time_series_covid_19_confirmed.csv')
names(data) <- c("State/Province", "Country/Region", "Latitude", "Longitude", "1/22", "1/23", "1/24", "1/25","1/26", "1/27", "1/28", "1/29", "1/30", "1/31", "2/1", "2/2", "2/3", "2/4", "2/5", "2/6", "2/7", "2/8", "2/9", "2/10", "2/11", "2/12", "2/13", "2/14", "2/15", "2/16", "2/17", "2/18", "2/19", "2/20", "2/21", "2/22", "2/23", "2/24", "2/25", "2/26", "2/27", "2/28", "2/29", "3/1", "3/2", "3/3", "3/4", "3/5", "3/6", "3/7", "3/8", "3/9", "3/10", "3/11", "3/12", "3/13", "3/14", "3/15", "3/16", "3/17", "3/18", "3/19")
```

```{r}
data <- cbind(data, rowSums(data[5:62]))
data
names(data)[63] <- "Positive_Population"
```

```{r}
sick_countries <- data %>%
  arrange(desc(rowSums(data[5:62]))) %>%
  head(480) %>%
  select(Latitude, Longitude)
glimpse(sick_countries)
```

```{r}
city_clusters <- sick_countries %>%
  kmeans(centers = 6) %>%
  fitted("classes") %>%
  as.character()
sick_countries <- sick_countries %>% mutate(cluster = city_clusters)
sick_countries %>% ggplot(aes(x = Longitude, y = Latitude)) + geom_point(aes(color = cluster), alpha = 0.5) 
```

```{r}
WorldData <- map_data('world') %>% filter(region != "Antarctica") %>% fortify

city_clusters <- sick_countries %>%
  kmeans(centers = 6) %>%
  fitted("classes") %>%
  as.character()
sick_countries <- sick_countries %>% mutate(cluster = city_clusters)
sick_countries %>% ggplot(aes(x = Longitude, y = Latitude)) + geom_point(aes(color = cluster), alpha = 0.5) +  geom_map(data = WorldData, map = WorldData,
                  aes(x = long, y = lat, group = group, map_id=region),
                  fill = "white", colour = "#7f7f7f", size=0.5)
```


